---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: special-spoon
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    snippets:
      # Apply IP Forwarding before installing Docker to prevent messing with LXC networking
      - sysctl -p

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: bling
    install:
      - 1password

  - type: rpm-ostree
    repos:
      - 1password.repo
      - _copr:copr.fedorainfracloud.org:sneexy:zen-browser.repo
      - docker-ce.repo
      - terra.repo
    keys:
      - https://downloads.1password.com/linux/keys/1password.asc
    install:
      - micro # terminal text editor
      - zen-browser # browser based on firefox
      - zed # code editor
      - ranger # terminal file explorer
      - bat # cat alternative
      - eza # ls alternative
      - fzf # fuzzy finder
      - zoxide # kind of like cd
      - ripgrep # fast grep
      - tealdeer # get a tldr for commands
      - docker-ce # docker
      - docker-ce-cli # docker
      - containerd.io # docker
      - docker-buildx-plugin # docker
      - docker-compose-plugin # docker

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - com.discordapp.Discord # chat program
        - com.github.iwalton3.jellyfin-media-player # media player to stream from a jellyfin media server
        - com.github.johnfactotum.Foliate # e-book reader
        - com.github.tchx84.Flatseal # customize flatpaks (like setting jellyfin media player to not use wayland)
        - com.spotify.Client # for streaming music
    user: {} # Also add Flathub user repo, but no user packages

  - type: script
    snippets:
      - systemctl enable docker.socket

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
