---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: special-spoon
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia-open
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    snippets:
      # Apply IP Forwarding before installing Docker to prevent messing with LXC networking
      - sysctl -p

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: bling
    install:
      - 1password # password manager

  - type: rpm-ostree
    repos:
      - 1password.repo
      - docker-ce.repo
      - ghostty.repo
      - terra.repo
      - vscode.repo
      - niri.repo
    install:
      - micro # terminal text editor
      - zed # code editor
      - code # code editor, added for devcontainers
      - ranger # terminal file explorer
      - bat # cat alternative
      - eza # ls alternative
      - fzf # fuzzy finder
      - zoxide # kind of like cd
      - ripgrep # fast grep
      - tealdeer # get a tldr for commands
      - docker-ce # docker
      - docker-ce-cli # docker
      - containerd.io # docker
      - docker-buildx-plugin # docker
      - docker-compose-plugin # docker
      - firefox # replace flatpak version so 1pass integration works
      - foot # simple wayland terminal
      - ghostty # new fancy terminal
      - terminator # old reliable terminal
      - niri # scrollable tiling window manager
      - xwayland-satellite # to launch x11 programs under niri
      - fuzzel # application launcher
      - polkit-kde # niri needs a polkit
      - proton-pass-1.31.1-1.x86_64.rpm # proton password manager

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - com.discordapp.Discord # chat program
        - dev.vencord.Vesktop # discord client "fork", but supports screen sharing
        - com.github.iwalton3.jellyfin-media-player # media player to stream from a jellyfin media server
        - com.github.johnfactotum.Foliate # e-book reader
        - com.github.tchx84.Flatseal # customize flatpaks (like setting jellyfin media player to not use wayland)
        - com.spotify.Client # for streaming music
        - com.heroicgameslauncher.hgl # game launcher aggregator (gog and epic in one place)
        - com.github.PintaProject.Pinta # painting program
        - com.obsproject.Studio # for streaming from my computer (e.g. to twitch)
        - com.usebottles.bottles # manage wine "flasks"
      remove:
        - org.mozilla.firefox # installed via rpm
        # remove all the preinstalled stuff i don't care about
        - org.gnome.clocks
        - org.gnome.Weather
        - org.gnome.baobab
        - org.gnome.Logs
        - org.gnome.Contacts
        - org.gnome.Characters
        - org.gnome.Calendar
        - io.missioncenter.MissionCenter
        - io.github.nokse22.Exhibit
        - de.leopoldluley.Clapgrep
    user: {} # Also add Flathub user repo, but no user packages

  - type: systemd
    system:
      enabled:
        - docker.socket
        - tailscaled

  - type: script
    snippets:
      # Stop RPM Firefox from screwing with the homepage by deleting all lines containing their startpage URL
      - sed -i '/start.fedoraproject.org/d' /usr/lib64/firefox/browser/defaults/preferences/firefox-redhat-default-prefs.js

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
